# Re-run control run with daily output

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import xarray as xr
import matplotlib.pyplot as plt

import atlas

## Define experiment and phase

In [3]:
cdr_forcing = "DOR"
vintage = "001"

In [4]:
calc = atlas.global_irf_map(cdr_forcing, vintage)

## Table of experiments

In [5]:
calc.df

,blueprint,polygon,polygon_master,basin,start_date,cdr_forcing,cdr_forcing_files,cdr_forcing_varnames,simulation_key,refdate,stop_n,wallclock,curtail_output,beta_file
case,,,,,,,,,,,,,,
smyle.cdr-atlas-v0.control.001,smyle,NaN,NaN,None,1999-01,None,None,NaN,baseline,0347-01-01,16,48:00:00,False,NaN
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-01-01_00000.001,smyle,0.0,0.0,North_Atlantic_basin,1999-01,DOR,[/global/cfs/projectdirs/m4746/Projects/OAE-Ef...,NaN,glb-dor_North_Atlantic_basin_000_1999-01-01_00000,0347-01-01,1,10:00:00,True,NaN
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-04-01_00001.001,smyle,0.0,0.0,North_Atlantic_basin,1999-04,DOR,[/global/cfs/projectdirs/m4746/Projects/OAE-Ef...,NaN,glb-dor_North_Atlantic_basin_000_1999-04-01_00001,0347-04-01,1,10:00:00,True,NaN
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-07-01_00002.001,smyle,0.0,0.0,North_Atlantic_basin,1999-07,DOR,[/global/cfs/projectdirs/m4746/Projects/OAE-Ef...,NaN,glb-dor_North_Atlantic_basin_000_1999-07-01_00002,0347-07-01,1,10:00:00,True,NaN
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-10-01_00003.001,smyle,0.0,0.0,North_Atlantic_basin,1999-10,DOR,[/global/cfs/projectdirs/m4746/Projects/OAE-Ef...,NaN,glb-dor_North_Atlantic_basin_000_1999-10-01_00003,0347-10-01,1,10:00:00,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_038_1999-10-01_02755.001,smyle,38.0,688.0,Southern_Ocean,1999-10,DOR,[/global/cfs/projectdirs/m4746/Projects/OAE-Ef...,NaN,glb-dor_Southern_Ocean_038_1999-10-01_02755,0347-10-01,1,10:00:00,True,NaN
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_039_1999-01-01_02756.001,smyle,39.0,689.0,Southern_Ocean,1999-01,DOR,[/global/cfs/projectdirs/m4746/Projects/OAE-Ef...,NaN,glb-dor_Southern_Ocean_039_1999-01-01_02756,0347-01-01,1,10:00:00,True,NaN
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_039_1999-04-01_02757.001,smyle,39.0,689.0,Southern_Ocean,1999-04,DOR,[/global/cfs/projectdirs/m4746/Projects/OAE-Ef...,NaN,glb-dor_Southern_Ocean_039_1999-04-01_02757,0347-04-01,1,10:00:00,True,NaN
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_039_1999-07-01_02758.001,smyle,39.0,689.0,Southern_Ocean,1999-07,DOR,[/global/cfs/projectdirs/m4746/Projects/OAE-Ef...,NaN,glb-dor_Southern_Ocean_039_1999-07-01_02758,0347-07-01,1,10:00:00,True,NaN
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_039_1999-10-01_02759.001,smyle,39.0,689.0,Southern_Ocean,1999-10,DOR,[/global/cfs/projectdirs/m4746/Projects/OAE-Ef...,NaN,glb-dor_Southern_Ocean_039_1999-10-01_02759,0347-10-01,1,10:00:00,True,NaN

## Check status

In [6]:
%%time
df = calc.df_case_status
df

CPU times: user 7.17 ms, sys: 2.34 ms, total: 9.51 ms
Wall time: 242 ms

,build,submitted,run_completed,archive,error,error_count,timestamp_run,JobId,JobState,Queued,yr_per_day,pe-hr_per_yr
case,,,,,,,,,,,,
smyle.cdr-atlas-v0.control.001,True,False,False,False,False,0,NaT,None,None,False,NaN,NaN
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-01-01_00000.001,True,True,True,True,False,0,2025-07-19 21:50:30,None,None,False,53.86,399.22

## Build the model for each experiment

In [7]:
clobber_list = calc.check_cases()
clobber_list

the following cases may have failed:
  smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-01-01_00000.001

['smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-01-01_00000.001']

In [8]:
len(clobber_list)

1

In [9]:
phase = "deploy"
clobber = True

In [10]:
calc.build(
    phase=phase, 
    clobber=clobber, 
    clobber_list=clobber_list, 
    just_these_cases=[
        "smyle.cdr-atlas-v0.control.001"
        #"smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-01-01_00000.001",
    ]
)

Submitted batch job 50024937

In [11]:
%%time
df = calc.df_case_status
df

CPU times: user 21 μs, sys: 18 μs, total: 39 μs
Wall time: 43.2 μs

,build,submitted,run_completed,archive,error,error_count,timestamp_run,JobId,JobState,Queued,yr_per_day,pe-hr_per_yr
case,,,,,,,,,,,,
smyle.cdr-atlas-v0.control.001,True,False,False,False,False,0,NaT,None,None,False,NaN,NaN
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-01-01_00000.001,True,True,True,True,False,0,2025-07-19 21:50:30,None,None,False,53.86,399.22

## Run the simulations

In [12]:
n_jobs = calc.compute(
    n_bundle=1, 
    bundle_queue="debug", 
    just_these_cases=[
        "smyle.cdr-atlas-v0.control.001"
        #"smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-01-01_00000.001", 
    ]
)

debug

## The simulation produced daily outputs

In [13]:
import xarray as xr

In [14]:
base_path = "/pscratch/sd/n/nloose/Ocean-CDR-Atlas-v0/smyle.cdr-atlas-v0.control.001/run/"

In [15]:
ds = xr.open_dataset(f"{base_path}/smyle.cdr-atlas-v0.control.001.pop.h.nday1.0347-01-01.nc", decode_times=False)

In [16]:
ds

<xarray.Dataset> Size: 4GB
Dimensions:                 (time: 31, d2: 2, z_t: 60, z_w: 60, nlat: 384,
                             nlon: 320, z_t_150m: 15, z_w_top: 60, z_w_bot: 60)
Coordinates:
  * time                    (time) float64 248B 1.267e+05 ... 1.267e+05
  * z_t                     (z_t) float32 240B 500.0 1.5e+03 ... 5.375e+05
  * z_t_150m                (z_t_150m) float32 60B 500.0 1.5e+03 ... 1.45e+04
  * z_w                     (z_w) float32 240B 0.0 1e+03 ... 5e+05 5.25e+05
  * z_w_top                 (z_w_top) float32 240B 0.0 1e+03 ... 5e+05 5.25e+05
  * z_w_bot                 (z_w_bot) float32 240B 1e+03 2e+03 ... 5.5e+05
    ULONG                   (nlat, nlon) float64 983kB ...
    ULAT                    (nlat, nlon) float64 983kB ...
    TLONG                   (nlat, nlon) float64 983kB ...
    TLAT                    (nlat, nlon) float64 983kB ...
Dimensions without coordinates: d2, nlat, nlon
Data variables: (12/57)
    time_bound              (time, d2) float64 496B ...
    dz                      (z_t) float32 240B ...
    dzw                     (z_w) float32 240B ...
    KMT                     (nlat, nlon) float64 983kB ...
    KMU                     (nlat, nlon) float64 983kB ...
    REGION_MASK             (nlat, nlon) float64 983kB ...
    ...                      ...
    SST                     (time, nlat, nlon) float32 15MB ...
    SSS                     (time, nlat, nlon) float32 15MB ...
    PO4                     (time, z_t, nlat, nlon) float32 914MB ...
    SiO3                    (time, z_t, nlat, nlon) float32 914MB ...
    DIC                     (time, z_t, nlat, nlon) float32 914MB ...
    ALK                     (time, z_t, nlat, nlon) float32 914MB ...
Attributes:
    title:             smyle.cdr-atlas-v0.control.001
    history:           none
    Conventions:       CF-1.0; http://www.cgd.ucar.edu/cms/eaton/netcdf/CF-cu...
    time_period_freq:  day_1
    model_doi_url:     https://doi.org/10.5065/D67H1H0V
    contents:          Diagnostic and Prognostic Variables
    source:            CCSM POP2, the CCSM Ocean Component
    revision:          $Id$
    calendar:          All years have exactly  365 days.
    start_time:        This dataset was created on 2026-01-12 at 13:06:49.7
    cell_methods:      cell_methods = time: mean ==> the variable values are ...